SELECT U.USER_ID, U.USERNAME, U.DEPTNAME, MM.PRICE, MM.REASON, MM.REVIEW_DATE SH_DATE, MM.PROPORTION FC_RATIO, MM.FEE_NAME, '买卖' CONTRACT_TYPE, MM.CONTRACT_CODE, MM.USER_ID, MM.STORE_USER_ID,USR.username FC_USER,STORE_USER.username FC_STORE_USER,AREA_USER.username FC_AREA_USER
FROM   REPORT_USER_DEPT_INFO U
LEFT   JOIN REPORT_MM_FEE_INFO MM
ON     U.USER_ID = MM.USER_ID
AND    TO_CHAR(MM.INPUT_DATE, 'YYYY-MM-DD') >= concat(to_char(VIEW_DATE.GET_DATE,'yyyy-MM'),'-01')
AND    TO_CHAR(MM.INPUT_DATE, 'YYYY-MM-DD') <= to_char(last_day(VIEW_DATE.GET_DATE),'yyyy-MM-dd')
AND    TO_CHAR(MM.REVIEW_DATE, 'YYYY-MM-DD') >= concat(to_char(VIEW_DATE.GET_DATE,'yyyy-MM'),'-01')
AND    TO_CHAR(MM.REVIEW_DATE, 'YYYY-MM-DD') <= to_char(last_day(VIEW_DATE.GET_DATE),'yyyy-MM-dd')
JOIN   REPORT_USER_DEPT_INFO USR
ON     MM.user_id = USR.user_id
JOIN   REPORT_USER_DEPT_INFO STORE_USER
ON     MM.store_user_id = STORE_USER.user_id
JOIN   REPORT_USER_DEPT_INFO AREA_USER
ON     MM.area_user_id = AREA_USER.user_id
WHERE  U.USER_ID = '${USER_ID}'

UNION ALL
SELECT U.USER_ID, U.USERNAME, U.DEPTNAME, MM.PRICE, MM.REASON, MM.REVIEW_DATE SH_DATE, MM.PROPORTION FC_RATIO, MM.FEE_NAME, '买卖' CONTRACT_TYPE, MM.CONTRACT_CODE, MM.USER_ID, MM.STORE_USER_ID,USR.username FC_USER,STORE_USER.username FC_STORE_USER,AREA_USER.username FC_AREA_USER
FROM   REPORT_USER_DEPT_INFO U
LEFT   JOIN REPORT_MM_FEE_INFO MM
ON     U.USER_ID = MM.USER_ID
AND    TO_CHAR(MM.INPUT_DATE, 'YYYY-MM-DD') >= concat(to_char(VIEW_DATE.GET_DATE,'yyyy-MM'),'-01')
AND    TO_CHAR(MM.INPUT_DATE, 'YYYY-MM-DD') <= to_char(last_day(VIEW_DATE.GET_DATE),'yyyy-MM-dd')
AND    TO_CHAR(MM.REVIEW_DATE, 'YYYY-MM-DD') < concat(to_char(VIEW_DATE.GET_DATE,'yyyy-MM'),'-01')
AND    MM.PRICE >= 0
JOIN   REPORT_USER_DEPT_INFO USR
ON     MM.user_id = USR.user_id
JOIN   REPORT_USER_DEPT_INFO STORE_USER
ON     MM.store_user_id = STORE_USER.user_id
JOIN   REPORT_USER_DEPT_INFO AREA_USER
ON     MM.area_user_id = AREA_USER.user_id
WHERE  U.USER_ID = '${USER_ID}'

UNION ALL
SELECT U.USER_ID, U.USERNAME, U.DEPTNAME, ZL.PRICE, ZL.REASON, ZL.REVIEW_DATE SH_DATE, ZL.PROPORTION FC_RATIO, ZL.FEE_NAME, '租赁' CONTRACT_TYPE, ZL.CONTRACT_CODE, ZL.USER_ID, ZL.STORE_USER_ID,USR.username FC_USER,STORE_USER.username FC_STORE_USER,AREA_USER.username FC_AREA_USER
FROM   REPORT_USER_DEPT_INFO U
LEFT   JOIN REPORT_ZL_FEE_INFO ZL
ON     U.USER_ID = ZL.USER_ID
AND    TO_CHAR(ZL.INPUT_DATE, 'YYYY-MM-DD') >= concat(to_char(VIEW_DATE.GET_DATE,'yyyy-MM'),'-01')
AND    TO_CHAR(ZL.INPUT_DATE, 'YYYY-MM-DD') <= to_char(last_day(VIEW_DATE.GET_DATE),'yyyy-MM-dd')
AND    TO_CHAR(ZL.REVIEW_DATE, 'YYYY-MM-DD') >= concat(to_char(VIEW_DATE.GET_DATE,'yyyy-MM'),'-01')
AND    TO_CHAR(ZL.REVIEW_DATE, 'YYYY-MM-DD') <= to_char(last_day(VIEW_DATE.GET_DATE),'yyyy-MM-dd')
JOIN   REPORT_USER_DEPT_INFO USR
ON     ZL.user_id = USR.user_id
JOIN   REPORT_USER_DEPT_INFO STORE_USER
ON     ZL.store_user_id = STORE_USER.user_id
JOIN   REPORT_USER_DEPT_INFO AREA_USER
ON     ZL.area_user_id = AREA_USER.user_id
WHERE  U.USER_ID = '${USER_ID}'

UNION ALL
SELECT U.USER_ID, U.USERNAME, U.DEPTNAME, ZL.PRICE, ZL.REASON, ZL.REVIEW_DATE SH_DATE, ZL.PROPORTION FC_RATIO, ZL.FEE_NAME, '租赁' CONTRACT_TYPE, ZL.CONTRACT_CODE, ZL.USER_ID, ZL.STORE_USER_ID,USR.username FC_USER,STORE_USER.username FC_STORE_USER,AREA_USER.username FC_AREA_USER
FROM   REPORT_USER_DEPT_INFO U
LEFT   JOIN REPORT_ZL_FEE_INFO ZL
ON     U.USER_ID = ZL.USER_ID
AND    TO_CHAR(ZL.INPUT_DATE, 'YYYY-MM-DD') >= concat(to_char(VIEW_DATE.GET_DATE,'yyyy-MM'),'-01')
AND    TO_CHAR(ZL.INPUT_DATE, 'YYYY-MM-DD') <= to_char(last_day(VIEW_DATE.GET_DATE),'yyyy-MM-dd')
AND    TO_CHAR(ZL.REVIEW_DATE, 'YYYY-MM-DD') < concat(to_char(VIEW_DATE.GET_DATE,'yyyy-MM'),'-01')
AND    ZL.PRICE >= 0
JOIN   REPORT_USER_DEPT_INFO USR
ON     ZL.user_id = USR.user_id
JOIN   REPORT_USER_DEPT_INFO STORE_USER
ON     ZL.store_user_id = STORE_USER.user_id
JOIN   REPORT_USER_DEPT_INFO AREA_USER
ON     ZL.area_user_id = AREA_USER.user_id
WHERE  U.USER_ID = '${USER_ID}'

UNION ALL
SELECT U.USER_ID, U.USERNAME, U.DEPTNAME, DL.PRICE, DL.REASON, DL.REVIEW_DATE SH_DATE, DL.PROPORTION FC_RATIO, DL.FEE_NAME, '新房' CONTRACT_TYPE, DL.CONTRACT_CODE, DL.USER_ID, DL.STORE_USER_ID,USR.username FC_USER,STORE_USER.username FC_STORE_USER,AREA_USER.username FC_AREA_USER
FROM   REPORT_USER_DEPT_INFO U
LEFT   JOIN REPORT_DL_FEE_INFO DL
ON     U.USER_ID = DL.USER_ID
AND    TO_CHAR(DL.INPUT_DATE, 'YYYY-MM-DD') >= concat(to_char(VIEW_DATE.GET_DATE,'yyyy-MM'),'-01')
AND    TO_CHAR(DL.INPUT_DATE, 'YYYY-MM-DD') <= to_char(last_day(VIEW_DATE.GET_DATE),'yyyy-MM-dd')
AND    TO_CHAR(DL.REVIEW_DATE, 'YYYY-MM-DD') >= concat(to_char(VIEW_DATE.GET_DATE,'yyyy-MM'),'-01')
AND    TO_CHAR(DL.REVIEW_DATE, 'YYYY-MM-DD') <= to_char(last_day(VIEW_DATE.GET_DATE),'yyyy-MM-dd')
JOIN   REPORT_USER_DEPT_INFO USR
ON     DL.user_id = USR.user_id
JOIN   REPORT_USER_DEPT_INFO STORE_USER
ON     DL.store_user_id = STORE_USER.user_id
JOIN   REPORT_USER_DEPT_INFO AREA_USER
ON     DL.area_user_id = AREA_USER.user_id
WHERE  U.USER_ID = '${USER_ID}'

UNION ALL
SELECT U.USER_ID, U.USERNAME, U.DEPTNAME, DL.PRICE, DL.REASON, DL.REVIEW_DATE SH_DATE, DL.PROPORTION FC_RATIO, DL.FEE_NAME, '新房' CONTRACT_TYPE, DL.CONTRACT_CODE, DL.USER_ID, DL.STORE_USER_ID,USR.username FC_USER,STORE_USER.username FC_STORE_USER,AREA_USER.username FC_AREA_USER
FROM   REPORT_USER_DEPT_INFO U
LEFT   JOIN REPORT_DL_FEE_INFO DL
ON     U.USER_ID = DL.USER_ID
AND    TO_CHAR(DL.INPUT_DATE, 'YYYY-MM-DD') >= concat(to_char(VIEW_DATE.GET_DATE,'yyyy-MM'),'-01')
AND    TO_CHAR(DL.INPUT_DATE, 'YYYY-MM-DD') <= to_char(last_day(VIEW_DATE.GET_DATE),'yyyy-MM-dd')
AND    TO_CHAR(DL.REVIEW_DATE, 'YYYY-MM-DD') < concat(to_char(VIEW_DATE.GET_DATE,'yyyy-MM'),'-01')
AND    DL.PRICE >= 0
JOIN   REPORT_USER_DEPT_INFO USR
ON     DL.user_id = USR.user_id
JOIN   REPORT_USER_DEPT_INFO STORE_USER
ON     DL.store_user_id = STORE_USER.user_id
JOIN   REPORT_USER_DEPT_INFO AREA_USER
ON     DL.area_user_id = AREA_USER.user_id
WHERE  U.USER_ID = '${USER_ID}'