SELECT D.NAME DEPTNAME, USR.USERNAME USERNAME, DETAIL1.PRICE PRICE, DETAIL1.PROPORTION FC_RATIO, DETAIL1.REASON REASON, FEE.REVIEW_DATE SH_DATE, FEE.FEE_NAME FEE_NAME, FEE.CONTRACT_TYPE CONTRACT_TYPE, MM.CONTRACT_CODE CONTRACT_CODE, DETAIL1.USER_ID USER_ID, DETAIL1.DEPT_ID DEPT_ID
FROM   NEW_FIN_PROFIT_DETAIL DETAIL1, BIZ_CONTRACT_FEE FEE, BIZ_MM_CONTRACT MM, SYS_USER USR, SYS_DEPARTMENT D
WHERE  DETAIL1.FEE_ID = FEE.ID
AND    FEE.CONTRACT_ID = MM.ID
AND    DETAIL1.STATUS = '已分成'
AND    DETAIL1.IS_REC = 0
AND    MM.STATUS = '已审核'
AND    MM.IS_REC = 0
AND    USR.ID = DETAIL1.USER_ID
AND    D.ID = DETAIL1.DEPT_ID
AND    TO_CHAR(DETAIL1.INPUT_DATE, 'YYYY-MM-DD') >= concat(to_char(VIEW_DATE.GET_DATE,'yyyy-MM'),'-01')
AND    TO_CHAR(DETAIL1.INPUT_DATE, 'YYYY-MM-DD') <= to_char(last_day(VIEW_DATE.GET_DATE),'yyyy-MM-dd')
AND    USR.USERNAME LIKE '%${USERNAME}%'
UNION all
SELECT D.NAME DEPTNAME, USR.USERNAME USERNAME, DETAIL1.PRICE PRICE, DETAIL1.PROPORTION FC_RATIO, DETAIL1.REASON REASON, FEE.REVIEW_DATE SH_DATE, FEE.FEE_NAME FEE_NAME, FEE.CONTRACT_TYPE CONTRACT_TYPE, ZL.CONTRACT_CODE CONTRACT_CODE, DETAIL1.USER_ID USER_ID, DETAIL1.DEPT_ID DEPT_ID
FROM   NEW_FIN_PROFIT_DETAIL DETAIL1, BIZ_CONTRACT_FEE FEE, BIZ_ZL_CONTRACT ZL, SYS_USER USR, SYS_DEPARTMENT D
WHERE  DETAIL1.FEE_ID = FEE.ID
AND    FEE.CONTRACT_ID = ZL.ID
AND    DETAIL1.STATUS = '已分成'
AND    DETAIL1.IS_REC = 0
AND    ZL.STATUS = '已审核'
AND    ZL.IS_REC = 0
AND    USR.ID = DETAIL1.USER_ID
AND    D.ID = DETAIL1.DEPT_ID
AND    TO_CHAR(DETAIL1.INPUT_DATE, 'YYYY-MM-DD') >= concat(to_char(VIEW_DATE.GET_DATE,'yyyy-MM'),'-01')
AND    TO_CHAR(DETAIL1.INPUT_DATE, 'YYYY-MM-DD') <= to_char(last_day(VIEW_DATE.GET_DATE),'yyyy-MM-dd')
AND    USR.USERNAME LIKE '%${USERNAME}%'
ORDER BY SH_DATE DESC