SELECT USR.USER_ID, USR.USERNAME, USR.DEPTNAME, MM.PRICE, MM.REASON, MM.REVIEW_DATE SH_DATE, MM.PROPORTION FC_RATIO, MM.FEE_NAME, '买卖' CONTRACT_TYPE, MM.CONTRACT_CODE, MM.USER_ID, MM.STORE_USER_ID,USR.username FC_USER,STORE_USER.username FC_STORE_USER,AREA_USER.username FC_AREA_USER
FROM   REPORT_MM_FEE_INFO MM
LEFT   JOIN BIZ_CONTRACT_FEE FEE
ON     MM.RECEIPT_NUMBER = FEE.RECEIPT_NUMBER
AND    FEE.PRICE >= 0
JOIN   REPORT_USER_DEPT_INFO USR
ON     MM.user_id = USR.user_id
JOIN   REPORT_USER_DEPT_INFO STORE_USER
ON     MM.store_user_id = STORE_USER.user_id
JOIN   REPORT_USER_DEPT_INFO AREA_USER
ON     MM.area_user_id = AREA_USER.user_id
WHERE  FEE.RECEIPT_NUMBER = '${SJ}'
AND    MM.price >= 0

UNION ALL
SELECT USR.USER_ID, USR.USERNAME, USR.DEPTNAME, ZL.PRICE, ZL.REASON, ZL.REVIEW_DATE SH_DATE, ZL.PROPORTION FC_RATIO, ZL.FEE_NAME, '租赁' CONTRACT_TYPE, ZL.CONTRACT_CODE, ZL.USER_ID, ZL.STORE_USER_ID,USR.username FC_USER,STORE_USER.username FC_STORE_USER,AREA_USER.username FC_AREA_USER
FROM   REPORT_ZL_FEE_INFO ZL
LEFT   JOIN BIZ_CONTRACT_FEE FEE
ON     ZL.RECEIPT_NUMBER = FEE.RECEIPT_NUMBER
AND    FEE.PRICE >= 0
JOIN   REPORT_USER_DEPT_INFO USR
ON     ZL.user_id = USR.user_id
JOIN   REPORT_USER_DEPT_INFO STORE_USER
ON     ZL.store_user_id = STORE_USER.user_id
JOIN   REPORT_USER_DEPT_INFO AREA_USER
ON     ZL.area_user_id = AREA_USER.user_id
WHERE  FEE.RECEIPT_NUMBER = '${SJ}'
AND    ZL.price >= 0
/*
UNION ALL
SELECT USR.USER_ID, USR.USERNAME, USR.DEPTNAME, DL.PRICE, DL.REASON, DL.REVIEW_DATE SH_DATE, DL.PROPORTION FC_RATIO, DL.FEE_NAME, '新房' CONTRACT_TYPE, DL.CONTRACT_CODE, DL.USER_ID, DL.STORE_USER_ID,USR.username FC_USER,STORE_USER.username FC_STORE_USER,AREA_USER.username FC_AREA_USER
FROM   REPORT_DL_FEE_INFO DL
LEFT   JOIN BIZ_CONTRACT_FEE FEE
ON     DL.RECEIPT_NUMBER = FEE.RECEIPT_NUMBER
AND    FEE.PRICE >= 0
JOIN   REPORT_USER_DEPT_INFO USR
ON     DL.user_id = USR.user_id
JOIN   REPORT_USER_DEPT_INFO STORE_USER
ON     DL.store_user_id = STORE_USER.user_id
JOIN   REPORT_USER_DEPT_INFO AREA_USER
ON     DL.area_user_id = AREA_USER.user_id
WHERE  FEE.RECEIPT_NUMBER = '${SJ}'
AND    DL.price >= 0
*/
